"use client"; 
// ^--- هدا السطر هو مفتاح الحل النهائي

import { motion, AnimatePresence } from "framer-motion";
import { useState, useEffect } from "react";

export default function Home() {
  const [index, setIndex] = useState(0);
  const notionData = {
    seo_title: "POTransfora | Algorithmic Justice & Digital Sovereignty Protocol",
    seo_description: "• Leading the future with the Organizational DNA Protocol and Cyber-Human Immunity. Discover the Sovereign Treasury and the Immortal Digital Mentor within POTransfora.",
    brand_identity: "POTRANSFORA X SOVEREIGN MINIMALISM.",
    dynamic_keywords: "Future".split(","),
    inspiring_names: "".split(","),
    quote: ""
  };

  useEffect(() => {
    if (notionData.dynamic_keywords.length > 1) {
      const timer = setInterval(() => {
        setIndex((prev) => (prev + 1) % notionData.dynamic_keywords.length);
      }, 3000);
      return () => clearInterval(timer);
    }
  }, [notionData.dynamic_keywords]);

  return (
    <div className="flex min-h-screen flex-col bg-[#050505] text-white selection:bg-[#00A3FF] overflow-x-hidden font-sans">
      <header className="fixed top-0 z-50 w-full border-b border-white/10 bg-black/80 backdrop-blur-md px-6 py-4 flex justify-between items-center">
        <div className="flex items-center gap-3">
          <img src="https://r.jina.ai/i/0c4664c126564614be75276e036e8b7d" className="h-10 w-10 rounded-xl" alt="Logo" />
          <span className="text-xl font-black tracking-tighter uppercase italic">POTRANSFORA</span>
        </div>
        <div className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest px-3 py-1 border border-white/10 rounded-full">
           Live Deployment: 2026-02-26
        </div>
      </header>

      <main className="flex-1 flex flex-col items-center justify-center pt-20 px-6 text-center">
        <section className="space-y-6 max-w-5xl">
          <motion.h2 
            initial={{ opacity: 0 }} animate={{ opacity: 1 }}
            className="text-[10px] font-bold tracking-[0.8em] text-[#00A3FF] uppercase"
          >
            {notionData.brand_identity}
          </motion.h2>
          
          <h1 className="text-6xl md:text-9xl font-black tracking-tighter leading-none uppercase">
            Empowering <br/>
            <AnimatePresence mode="wait">
              <motion.span 
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                className="text-[#00A3FF] inline-block"
              >
                {notionData.dynamic_keywords[index]}
              </motion.span>
            </AnimatePresence>
          </h1>
        </section>

        <div className="my-32 w-full border-y border-white/5 py-12 overflow-hidden bg-zinc-900/10">
          <motion.div 
            animate={{ x: ["0%", "-50%"] }} 
            transition={{ repeat: Infinity, duration: 30, ease: "linear" }} 
            className="flex whitespace-nowrap"
          >
            {[...notionData.inspiring_names, ...notionData.inspiring_names].map((name, i) => (
              <span key={i} className="mx-12 text-4xl font-black italic opacity-10 uppercase tracking-tighter">{name}</span>
            ))}
          </motion.div>
        </div>

        <section className="max-w-3xl border-l-4 border-[#00A3FF] pl-10 text-left">
          <motion.p 
            initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }}
            className="text-2xl md:text-4xl font-light italic leading-relaxed text-zinc-300"
          >
            "{notionData.quote}"
          </motion.p>
        </section>
      </main>

      <footer className="p-10 text-[9px] text-zinc-700 font-mono tracking-[0.3em] text-center uppercase border-t border-white/5 mt-20">
        Generated by Potransfora Engine v2.6 • Sovereign Digital Identity
      </footer>
    </div>
  );
}
